// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_includes': '',
//   'precision': -1,
//   'quadrature_degree': -1,
//   'quadrature_rule': 'auto',
//   'representation': 'auto',
//   'scalar_type': 'double'}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_ffcx_element_6d766abed2d162c64a034b2be3e0959bb28ce126_finite_element_main(void);

ufc_finite_element* create_ffcx_element_f45206f2360ec2373cb779c9b8643d16ff5a6298_finite_element_main(void);

ufc_dofmap* create_ffcx_element_6d766abed2d162c64a034b2be3e0959bb28ce126_dofmap_main(void);

ufc_dofmap* create_ffcx_element_f45206f2360ec2373cb779c9b8643d16ff5a6298_dofmap_main(void);

ufc_coordinate_mapping* create_ffcx_coordinate_mapping_312062e1c9db04d57b844b7d83e2b382876e6017_coordinate_mapping_main(void);

ufc_integral* create_poisson_cell_integral_01009634762660f34296b73fe0fefcd3ed8d9be6_otherwise(void);

ufc_integral* create_poisson_cell_integral_36e08ac5d2e5b6b5e2272fc4c04506b4401043c0_otherwise(void);

ufc_integral* create_poisson_exterior_facet_integral_36e08ac5d2e5b6b5e2272fc4c04506b4401043c0_otherwise(void);

ufc_form* create_poisson_form_01009634762660f34296b73fe0fefcd3ed8d9be6(void);

ufc_form* create_poisson_form_36e08ac5d2e5b6b5e2272fc4c04506b4401043c0(void);


// Typedefs for convenience pointers to functions (factories)
typedef ufc_function_space* (*ufc_function_space_factory_ptr)(void);
typedef ufc_form* (*ufc_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 2)
ufc_function_space* poisson_coefficientspace_f_create(void);
ufc_function_space* poisson_coefficientspace_g_create(void);

// Form function spaces helpers (form 'a')
ufc_function_space* poisson_form_a_functionspace_0_create(void);

ufc_function_space* poisson_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
/*   - No form coefficients */
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_a_create = create_poisson_form_01009634762660f34296b73fe0fefcd3ed8d9be6;

/*    Typedefs (function spaces for form_a) */
static const ufc_function_space_factory_ptr poisson_form_a_testspace_create = poisson_form_a_functionspace_0_create;
static const ufc_function_space_factory_ptr poisson_form_a_trialspace_create = poisson_form_a_functionspace_1_create;


 /* End coefficient typedefs */

// Form function spaces helpers (form 'L')
ufc_function_space* poisson_form_L_functionspace_0_create(void);

/* Coefficient function space typedefs for form "form_L" */
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_1_create = poisson_coefficientspace_f_create;
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_2_create = poisson_coefficientspace_g_create;
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_L_create = create_poisson_form_36e08ac5d2e5b6b5e2272fc4c04506b4401043c0;

/*    Typedefs (function spaces for form_L) */
static const ufc_function_space_factory_ptr poisson_form_L_testspace_create = poisson_form_L_functionspace_0_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_f_create = poisson_form_L__functionspace_1_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_g_create = poisson_form_L__functionspace_2_create;

 /* End coefficient typedefs */

/* Start high-level typedefs */
static const ufc_form_factory_ptr poisson_bilinearform_create = poisson_form_a_create;
static const ufc_form_factory_ptr poisson_linearform_create = poisson_form_L_create;

static const ufc_function_space_factory_ptr poisson_functionspace_create = poisson_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
