// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_includes': '',
//   'precision': -1,
//   'quadrature_degree': -1,
//   'quadrature_rule': 'auto',
//   'representation': 'auto',
//   'scalar_type': 'double'}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_ffcx_element_1ee64a2355a871fa915386f7ef336891c0917585_finite_element_main(void);

ufc_finite_element* create_ffcx_element_99c9f83792027cf9a7fc409e8fda7a49ebc2f8c0_finite_element_main(void);

ufc_dofmap* create_ffcx_element_1ee64a2355a871fa915386f7ef336891c0917585_dofmap_main(void);

ufc_dofmap* create_ffcx_element_99c9f83792027cf9a7fc409e8fda7a49ebc2f8c0_dofmap_main(void);

ufc_coordinate_mapping* create_ffcx_coordinate_mapping_9d3bdc89434fc278d0663d9c6a90aa186fd7ea21_coordinate_mapping_main(void);

ufc_integral* create_poisson_cell_integral_c3ed5abea4121f4e49ce1f6d193d5b113f4ccffb_otherwise(void);

ufc_integral* create_poisson_cell_integral_254b28159b14312c13c7c630f6d5e61a4f9163ff_otherwise(void);

ufc_integral* create_poisson_exterior_facet_integral_254b28159b14312c13c7c630f6d5e61a4f9163ff_otherwise(void);

ufc_form* create_poisson_form_c3ed5abea4121f4e49ce1f6d193d5b113f4ccffb(void);

ufc_form* create_poisson_form_254b28159b14312c13c7c630f6d5e61a4f9163ff(void);


// Typedefs for convenience pointers to functions (factories)
typedef ufc_function_space* (*ufc_function_space_factory_ptr)(void);
typedef ufc_form* (*ufc_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 2)
ufc_function_space* poisson_coefficientspace_f_create(void);
ufc_function_space* poisson_coefficientspace_g_create(void);

// Form function spaces helpers (form 'a')
ufc_function_space* poisson_form_a_functionspace_0_create(void);

ufc_function_space* poisson_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
/*   - No form coefficients */
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_a_create = create_poisson_form_c3ed5abea4121f4e49ce1f6d193d5b113f4ccffb;

/*    Typedefs (function spaces for form_a) */
static const ufc_function_space_factory_ptr poisson_form_a_testspace_create = poisson_form_a_functionspace_0_create;
static const ufc_function_space_factory_ptr poisson_form_a_trialspace_create = poisson_form_a_functionspace_1_create;


 /* End coefficient typedefs */

// Form function spaces helpers (form 'L')
ufc_function_space* poisson_form_L_functionspace_0_create(void);

/* Coefficient function space typedefs for form "form_L" */
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_1_create = poisson_coefficientspace_f_create;
static const ufc_function_space_factory_ptr poisson_form_L_functionspace_2_create = poisson_coefficientspace_g_create;
/*    Form helper */
static const ufc_form_factory_ptr poisson_form_L_create = create_poisson_form_254b28159b14312c13c7c630f6d5e61a4f9163ff;

/*    Typedefs (function spaces for form_L) */
static const ufc_function_space_factory_ptr poisson_form_L_testspace_create = poisson_form_L_functionspace_0_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_f_create = poisson_form_L__functionspace_1_create;
// static ufc_function_space_factory_ptr poisson_form_L_coefficientspace_g_create = poisson_form_L__functionspace_2_create;

 /* End coefficient typedefs */

/* Start high-level typedefs */
static const ufc_form_factory_ptr poisson_bilinearform_create = poisson_form_a_create;
static const ufc_form_factory_ptr poisson_linearform_create = poisson_form_L_create;

static const ufc_function_space_factory_ptr poisson_functionspace_create = poisson_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
